### ISSUE TITLE
Trading Strategy logo on Documentation pages (top left corner) to lead to the home page

### ISSUE THREAD

**Issue by tsorro** [tradingstrategy-ai/docs#1]
Could we follow the typical linking style and change the Trading Strategy logo's (top left corner) link on Documentation pages to point to the home page tradingstrategy.ai? I believe this is what most sites provide. 

![Image](https://user-images.githubusercontent.com/20061308/177553552-04e82c25-f86f-42e2-9e4b-646bdc8aa51a.png)

It is frustrating to look for the link to home page elsewhere.

**Comment by hieuh25** [comment]
This is done so I'm closing this issue
