### ISSUE TITLE
fix conflation between slippage and price impact

### ISSUE THREAD

**Issue by AlexTheLion123** [tradingstrategy-ai/docs#13]
The docs at [this page](https://tradingstrategy.ai/docs/programming/code-examples/price-impact.html) conflate price impact and slippage. Price impact = not enough liquidity, slippage = price changes during your trade due to other trades in the same pool

**Comment by kenkunz** [comment]
@AlexTheLion123 – FYI, everything under `/docs` path is maintained in the `docs` repo (vs `frontend`) – moving this issue there.
