### ISSUE TITLE
Docs not updated with new enum value

### ISSUE THREAD

**Issue by plamut** [tradingstrategy-ai/docs#14]
The client [documentation](https://tradingstrategy.ai/docs/programming/api/client/help/tradingstrategy.exchange.ExchangeType.html) on the `ExchangeType` enum does not include the latest member, `uniswap_v2_incompatible`, even though that change has been released in tradingstrategy clent and a [commit](https://github.com/tradingstrategy-ai/docs/commit/e81a7210e699d810daaa2ecbd14146b0a80d6ea7) broght the latest code changes.

This ticket is to investigate, what went wrong, and possibly fix a glitch in the docs pipeline.

**Comment by plamut** [comment]
Note to self - when this is resolved, also document the process in developer docs on how to update the client documentation on the website

**Comment by miohtama** [comment]
Docs build is now fixed and it correctly reads API modules. Thus, docs are updating again:

https://tradingstrategy.ai/docs/programming/api/client/help/tradingstrategy.exchange.ExchangeType.html#exchangetype
