### ISSUE TITLE
no docs/sitemap.xml

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/docs#26]
# Issue

Our main [sitemap.xml](https://tradingstrategy.ai/sitemap.xml) includes a reference to [docs/sitemap.xml](https://tradingstrategy.ai/docs/sitemap.xml), but this URL returns a `404`.

## Steps to reproduce

1. open https://tradingstrategy.ai/docs/sitemap.xml
2. note `404`

**Comment by miohtama** [comment]
It is called

https://tradingstrategy.ai/docs/sitemap-docs.xml

**Comment by AlexTheLion123** [comment]
@miohtama Which one should be changed, link in sitemap.xml or actual url

**Comment by miohtama** [comment]
Fix link in `frontend` repo
