### ISSUE TITLE
Enabling Typesense search

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/docs#63]
Things we need to have in-place to get Typesense production going on

- [x] Document the production instance of Typesense Docker (where it is running, how to restart)
- [x] How Github CI from `docs` repo will recrawl the documentation
- [x] How can one locally test Typesense integration

**Comment by miohtama** [comment]
Current document deployment is done by this Github Actions

https://github.com/tradingstrategy-ai/docs/blob/master/.github/workflows/build-and-deploy-docs.yml

**Comment by sontn1988** [comment]
I created document about typesense self host
https://github.com/tradingstrategy-ai/scratchpad/wiki/Selfhost-Typesense

**Comment by sontn1988** [comment]
I updated GITHUB CI in PR https://github.com/tradingstrategy-ai/docs/pull/62
